name: mchinetest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/makeup.png
    - assets/care.png
    - assets/gifts.png
    - assets/perfume.jpg
    - assets/nails.png
    - assets/lenses.png
    - assets/devices.png
    - assets/home.jpg

